### ISSUE TITLE
Broken variable in code

### ISSUE THREAD

**Issue by wish1832** [amc-heme/coding-help#2]
I ran this document to understand the general aim of the code, and ran into an issue on lines 90 and 91 of the MDS scVera_test.rmd document (as it appears in the most recent commit in the `Monica-Ransom` branch). These lines include the variable `p1236_bc`, which does not appear earlier in the code. I attempted to rename it to `p1236_barcode_clusters`, but when I ran it again it returned another error: 

```
p1236_filtered_alt <- 
  rbind(p1236_barcode_clusters, p1236_filtered_alt)
```
<span style="color='red';"> Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match </span>

What is the correct name of the variable?

**Comment by darlandm** [comment]
I editted this and merged to the main.  The variable needed is seurat_groups not p1236_bc.  Please let me know if more details about the goals of the code are necessary.
